name: Java Test Automation Framework for CI with Maven

on:
  #Trigger this workflow on pull requests
  pull_request:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 23 (or whichever version you need)
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin'
         java-version: '23'

    # Step 3: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    # Step 4: Cache Maven dependencies to speed up the build
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 5: Install project dependencies and build the project
    - name: Build with Maven
      run: mvn -f TestAutomation/TestAutomationFramework/pom.xml clean install -DskipTests 

    # Step 6: Set up and start the client and server
    - name: Start Client and Server
      run: |
        npm run setup
        npm run start &
        sleep 5

    # # Step 7: Check if the server is up
    # - name: Wait for Server to be Ready
    #   run: |
    #     count=0
    #     until curl --silent --fail http://localhost:8080; do
    #       ((count++))
    #       if [ $count -ge 30 ]; then
    #         echo "Server did not start in time."
    #         exit 1
    #       fi
    #       echo "Waiting for server..."
    #       sleep 5
    #     done
    #     echo "Server is up!"

    # Step 8: Run the tests
    - name: Run Selenium tests
      run: mvn -f TestAutomation/TestAutomationFramework/pom.xml test
