name: Java Test Automation Framework for CI with Maven

on:
  #Trigger this workflow on pull requests
  pull_request:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 23 (or whichever version you need)
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin'
         java-version: '23'

    # Step 3: Cache Maven dependencies to speed up the build
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install project dependencies and build the project
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 5: Run the tests
    - name: Run Selenium tests
      run: mvn test
