name: Manual Test Run

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 5: Wait for Server to be Ready
    - name: Wait for Server to be Ready
      shell: cmd
      run: |
        set count=0
        :wait_loop
        curl --silent --fail http://localhost:8080 >nul 2>nul
        if %errorlevel%==0 (
          echo Server is up!
        ) else (
          set /a count+=1
          if %count% geq 60 (
            echo Server did not start in time.
            exit /b 1
          )
          echo Waiting for server... attempt %count%
          timeout /t 5 >nul
          goto wait_loop
        )

    # Step 6: Run Tests
    - name: Run Tests
      run: npm test  # Replace with your test command

