name: Manual Test Run

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Internet Connectivity
      shell: pwsh
      run: |
        $count = 0
        while ($count -lt 60) {
          try {
            Invoke-RestMethod -Uri https://www.google.com -UseBasicParsing
            Write-Host "Internet connectivity is available!"
            break
          } catch {
            $count++
            Write-Host "Waiting for internet connectivity... attempt $count"
            Start-Sleep -Seconds 5
          }
        }
        if ($count -ge 60) {
          Write-Host "Internet connectivity could not be established in time."
          exit 1
        }
        
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    # Step 3: Install project dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Set up and start the client and server
    - name: Start Client and Server
      run: |
        npm run setup
        npm run start &
        echo "Server and client starting..."

    # Step 5: Wait for Server to be Ready
    - name: Wait for Server to be Ready
      shell: pwsh
      run: |
        $count = 0
        while ($count -lt 60) {
          try {
            Invoke-RestMethod -Uri http://localhost:8080 -UseBasicParsing
            Write-Host "Server is up!"
            break
          } catch {
            $count++
            Write-Host "Waiting for server... attempt $count"
            Start-Sleep -Seconds 5
          }
        }
        if ($count -ge 60) {
          Write-Host "Server did not start in time."
          exit 1
        }

    # Step 6: Run Tests
    - name: Run Tests
      run: npm test  # Replace with your test command
